### ISSUE TITLE
Build libbeam as Meta-package

### ISSUE THREAD

**Issue by adthoms** [BEAMRobotics/libbeam#229]
The original intent for libbeam was to install the software as if it were a library. We have no intention on releasing libbeam as a versioned library, and we will instead make it a standard catkin package. We will replace the current build system with a more simple [MetaPackage](http://wiki.ros.org/Metapackages) design, similar to how [Fuse](https://github.com/locusrobotics/fuse) is built

**Comment by nickcharron** [comment]
this was done in https://github.com/BEAMRobotics/libbeam/pull/234
